spring:
  datasource:
    url: jdbc:mysql://bonda.c03myocscluo.us-east-1.rds.amazonaws.com:3306
    username: root
    password: bonda123
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000
  flyway:
    enabled: true
    baseline-on-migrate: true
    default-schema: bonda
